liip_imagine:
    driver: "imagick"
    filter_sets:
        square:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
